services:
  xk6:
    depends_on:
      datadog:
        condition: service_healthy
    environment:
      - ENABLE_STATSD=true
      - K6_STATSD_ADDR=datadog:8125

  datadog:
    image: datadog/agent:latest
    container_name: datadog
    healthcheck:
      test: ["CMD", "agent", "health"]
      interval: 5s
      timeout: 3s
      retries: 5
    env_file:
      - .env.local    # Only load API key from here
    environment:
      - DD_SITE=datadoghq.eu
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=1
      - DD_HOSTNAME=k6-metrics
      - DD_DOGSTATSD_STATS_ENABLE=true
      - DD_PROCESS_AGENT_ENABLED=false
      - DOCKER_CONTENT_TRUST=1
      - DD_LOG_LEVEL=warn
    ports:
      - "8125:8125/udp"
