# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"

  # Maintain dependencies for Python
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"

  # Maintain hashes for the Docker image pip requirements
  - package-ecosystem: pip
    directory: /dockerfiles
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"

  # Maintain hashes for the Docker image agent dependencies
  - package-ecosystem: pip
    directory: /dockerfiles/agents
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"

  # Maintain dependencies for Docker (Python)
  - package-ecosystem: docker
    directories:
      - /dockerfiles/agents
      - /dockerfiles/app
      - /dockerfiles/tests
      - /dockerfiles/trustregistry
      - /dockerfiles/waypoint
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
    groups:
      docker-python:
        patterns:
          - "python*"
    ignore:
      - dependency-name: python
        # Ignore Python updates like 3.12 -> 3.13
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  # Maintain dependencies for Docker (Golang)
  - package-ecosystem: docker
    directories:
      - /scripts/k6
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
    groups:
      docker-golang:
        patterns:
          - "golang*"
