apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acapy-test.fullname" . }}
  labels:
    {{- include "acapy-test.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretConfig }}
  {{ $k }}: {{ tpl (toString $v) . }}
  {{- end }}
