# https://mise.jdx.dev
[tools]
"aqua:nats-io/natscli" = "0.2"
helm = "3"
helmfile = "1"
istioctl = "1.26"
jq = "latest"
kind = "0.29"
kubectl = "1.33"
poetry = "2.1"
pre-commit = "4.2"
python = "3.12"
tilt = "0.35"
usage = "latest"
yq = "latest"

[settings]
experimental = true
# Prevent Mise from running multiple jobs at the same time.
# Prevents `poetry install` from running in parallel which
#   results in multiple threads trying to write to the same file.
jobs = 1
# Install precompiled python binary
python_compile = false

[env]
DOCKER_HOST_OVERRIDE = "unix:///var/run/docker.sock"
KIND_CLUSTER_NAME = "acapy-cloud"
KIND_K8S_CONTEXT = "kind-{{env.KIND_CLUSTER_NAME}}"
KIND_DOCKER_CACHE = "docker-cache"
KIND_DOCKER_REGISTRY = "docker-registry"
KIND_DOCKER_REGISTRY_PORT = "5001"
# Use Python/Mise managed virtual environment
POETRY_VIRTUALENVS_CREATE = "false"
# Setup Python Virtual Environment
_.python.venv = { path = ".venv", create = true }

[tasks."poetry:install"]
description = "Poetry Install all dependencies"
run = "poetry install --with dev"

[tasks."poetry:update"]
description = "Poetry Update lock file"
run = "poetry lock --regenerate"

[tasks."tilt:up"]
description = "Start Tilt"
depends = ["kind:create"]
run = "tilt up"

[tasks."tilt:up:podman"]
description = "Start Tilt with Podman"
depends = ["kind:create"]
run = """
#!/bin/bash
mise set DOCKER_HOST=${DOCKER_HOST_OVERRIDE}
tilt up
"""

[tasks."tilt:up:expose"]
description = "Start Tilt with `--expose` flag"
depends = ["kind:create"]
run = "tilt up -- --expose"

[tasks."tilt:down"]
description = "Tilt Down"
run = "tilt down"

[tasks."tilt:down:destroy"]
description = "Tilt Down Destroy"
run = "tilt down -- --destroy"

[tasks."tilt:down:destroy:all"]
description = "Tilt Down Destroy everything, including Docker Cache"
run = "tilt down -- --destroy-all"

[tasks."tilt:ci"]
description = "Start Tilt in CI mode"
depends = ["kind:create"]
run = "tilt ci -- --no-build"

[tasks."kind:destroy:all"]
description = "Destroy Kind and delete Docker Registry & Cache"
run = """
#!/bin/bash
mise run kind:destroy --destroy-registry-containers
rm -rf tilt/docker
"""

[tasks.tests]
description = "Run all tests"
depends = ["poetry:install"]
run = """
#!/bin/bash
cp .env.example .env
source .env
poetry run pytest . --ignore ./tilt $@
"""

[tasks."tests:unit"]
description = "Run unit tests"
depends = ["poetry:install"]
run = "poetry run pytest -n auto --dist loadgroup -o 'norecursedirs=e2e' $@"

[tasks."tests:e2e"]
description = "Run e2e tests"
depends = ["poetry:install"]
run = """
#!/bin/bash
cp .env.example .env
source .env
poetry run pytest -n auto --dist loadgroup $(find . -type d -path '*/tests/e2e' -not -path './tilt*') $@
"""

[tasks.fmt]
description = "Format files"
run = """
#!/bin/bash
ruff check --fix
ruff format
find . -type f -name "Tiltfile" | while read -r file; do
  ruff format "$file"
done
"""

[tasks."fmt:check"]
description = "Check all files for formatting"
run = """
#!/bin/bash
ruff check
ruff format --check
find . -type f -name "Tiltfile" | while read -r file; do
  ruff format --check --diff "$file"
done
"""

[tasks.lint]
description = "Run static lint checks"
depends = ["lint:ruff", "lint:mypy"]

[tasks."lint:ruff"]
description = "Only run ruff static checks"
run = "ruff check"

[tasks."lint:mypy"]
description = "Only run mypy type checks"
run = """
#!/bin/bash
mypy . --ignore-missing-imports \
       --check-untyped-defs \
       --install-types --non-interactive
"""

[tasks."bootstrap:kubeconfig"]
description = "Set KUBECONFIG"
run = "mise set --env local --file mise.local.toml KUBECONFIG=$(pwd)/.mise/kubeconfig.yaml"

[hooks]
enter = ["mise bootstrap:kubeconfig"]
