# Docker Compose file used by Tilt to start Indy Ledger Nodes and Browser

services:
  ledger-browser:
    image: ${REGISTRY:-ghcr.io/didx-xyz}/acapy-cloud/ledger-nodes:${IMAGE_TAG:-latest}
    container_name: ledger-browser
    platform: linux/amd64
    command: "bash -c './scripts/start_webserver.sh'"
    environment:
      DOCKERHOST: ledger-nodes
      LEDGER_INSTANCE_NAME: Indy Ledger Browser
      LEDGER_SEED: ${LEDGER_SEED:-000000000000000000000000Trustee1}
      LOG_LEVEL: WARN
      MAX_FETCH: 50000
      # POOL_CONNECTION_ATTEMPTS: ${POOL_CONNECTION_ATTEMPTS:-5}
      # POOL_CONNECTION_DELAY: ${POOL_CONNECTION_DELAY:-10}
      REGISTER_NEW_DIDS: True
      RESYNC_TIME: 120
    ports:
      - ${WEB_SERVER_HOST_PORT:-9000}:8000
    volumes:
      - ledger-browser-cli:/home/indy/.indy-cli
      - ledger-browser-ledger:/home/indy/ledger
      - ./resources/ledger-nodes/aml.json:/home/indy/config/aml.json
      - ./resources/ledger-nodes/taa.json:/home/indy/config/taa.json
    networks:
      - kind
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ledger-browser:8000"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s
    depends_on:
      ledger-nodes:
        condition: service_healthy
  ledger-nodes:
    image: ${REGISTRY:-ghcr.io/didx-xyz}/acapy-cloud/ledger-nodes:${IMAGE_TAG:-latest}
    container_name: ledger-nodes
    platform: linux/amd64
    command: "bash -c './scripts/start_nodes.sh'"
    ports:
      - 0.0.0.0:9701:9701
      - 0.0.0.0:9702:9702
      - 0.0.0.0:9703:9703
      - 0.0.0.0:9704:9704
      - 0.0.0.0:9705:9705
      - 0.0.0.0:9706:9706
      - 0.0.0.0:9707:9707
      - 0.0.0.0:9708:9708
    environment:
      DOCKERHOST: ledger-nodes
      LOG_LEVEL: WARN
    volumes:
      - ledger-nodes:/home/indy/ledger
      - ./scripts/indy_healthcheck.sh:/home/indy/indy_healthcheck.sh
    networks:
      - kind
    healthcheck:
      test: ["CMD-SHELL", "/home/indy/indy_healthcheck.sh"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 30s

volumes:
  ledger-browser-cli:
  ledger-browser-ledger:
  ledger-nodes:

networks:
  kind:
    external: true
