fullnameOverride: did-registrar

replicaCount: 1

podAnnotations:
  sidecar.istio.io/proxyCPU: 10m

image:
  registry: docker.io
  name: universalregistrar/uni-registrar-web
  pullPolicy: Always
  tag: latest
  ## Multi-Arch Digest
  digest: sha256:440f44e04c8e20130fdf82f3f934b97da7d8c87e41c28f099576b829b7b9867f
  ## If things start breaking, this is a known good SHA but isn't Multi-Arch
  # digest: sha256:d02207a156cb97dd79d3515bc90a963d12660c4ca82382f77ae6b5d32351267f

env:
  ## Disable the Spring Boot banner
  SPRING_MAIN_BANNER_MODE: off
  ## Be very careful, this can do _a lot_ of logging
  ## Valid levels are: trace, debug, info, warn, error, fatal, off
  LOGGING_LEVEL_ROOT: warn
  LOGGING_LEVEL_uniregistrar: warn
  LOGGING_FORMAT: json # plain or json

service:
  appProtocol: http
  port: 9080
  containerPort: 9080

livenessProbe:
  tcpSocket:
    port: 9080
readinessProbe:
  tcpSocket:
    port: 9080
startupProbe:
  tcpSocket:
    port: 9080

extraVolumes:
  - name: tmp
    emptyDir: {}
extraVolumeMounts:
  - name: tmp
    mountPath: /tmp

podSecurityContext:
  fsGroup: 65534
securityContext:
  runAsUser: 65534
