fullnameOverride: driver-did-cheqd

replicaCount: 1

podAnnotations:
  sidecar.istio.io/proxyCPU: 10m

image:
  registry: ghcr.io
  name: cheqd/did-registrar
  pullPolicy: Always
  ## This is not currently Multi-Arch
  ## Pending merge/release of https://github.com/cheqd/did-registrar/pull/427
  tag: production-latest

service:
  appProtocol: http
  port: 3000
  containerPort: 3000

livenessProbe:
  tcpSocket:
    port: 3000
readinessProbe:
  tcpSocket:
    port: 3000
startupProbe:
  tcpSocket:
    port: 3000

secretData:
  FEE_PAYER_TESTNET_MNEMONIC: "" # Cheqd did-registrar uses testnet faucet by default
  # FEE_PAYER_MAINNET_MNEMONIC: "..."
