fullnameOverride: revocation-service

replicaCount: 2

podAnnotations:
  sidecar.istio.io/proxyCPU: 10m
  ad.datadoghq.com/revocation-service.logs: '[{"source": "python.uvicorn", "service": "revocation-service"}]'
  proxy.istio.io/config: |-
    proxyMetadata:
      ISTIO_META_IDLE_TIMEOUT: 0s
podLabels:
  admission.datadoghq.com/enabled: "true"

image:
  name: acapy-cloud/revocation-service
  pullPolicy: Always
  tag: master

command:
  - poetry
  - run
  - uvicorn
  - revocation_service.main:app
  - --log-config=/tmp/log_conf.yaml
  - --reload
  - --host
  - 0.0.0.0
  - --port
  - 3012

ingressDomain: cloudapi.127.0.0.1.nip.io
ingress:
  internal:
    enabled: true
    className: nginx
    rules:
      - host: revocation-service.{{ .Values.ingressDomain }}
        paths:
          - path: /

service:
  # if set, will run Pods on Node Network
  appProtocol: http
  hostNetwork: false
  port: 3012
  containerPort: 3012

livenessProbe:
  httpGet:
    path: /health/live
    port: "{{ trunc 15 .Release.Name }}"
readinessProbe:
  httpGet:
    path: /health/ready
    port: "{{ trunc 15 .Release.Name }}"
startupProbe:
  httpGet:
    path: /health/live
    port: "{{ trunc 15 .Release.Name }}"

lifecycle:
  preStop:
    exec:
      command:
        - /bin/sh
        - -c
        - sleep 15

# resources:
#   requests:
#     cpu: 100m
#     memory: 512Mi
#   limits:
#     cpu: 500m
#     memory: 1Gi

autoscaling:
  enabled: false

env:
  LOG_LEVEL: info
  OPENAPI_NAME: revocation-service
  PYTHONPATH: "/"
  ENABLE_SERIALIZE_LOGS: "FALSE"

podSecurityContext:
  fsGroup: 65534
securityContext:
  # Required for Tilt Live Reload
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0

extraVolumes:
  - name: logs
    emptyDir: {}
  - name: tmp
    emptyDir: {}
extraVolumeMounts:
  - name: logs
    mountPath: /logs
  - name: tmp
    mountPath: /tmp

podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: soft
  key: node.kubernetes.io/lifecycle
  values:
    - spot

configFiles:
  log_conf.yaml:
    path: /tmp/log_conf.yaml
    content: |-
      version: 1
      disable_existing_loggers: False
      formatters:
        default:
          "()": uvicorn.logging.DefaultFormatter
          format: '%(asctime)s %(name)s %(levelname)s %(message)s'
          use_colors: null
        access:
          "()": uvicorn.logging.AccessFormatter
          format: '%(asctime)s %(name)s %(levelname)s %(client_addr)s - "%(request_line)s" %(status_code)s'
      handlers:
        default:
          formatter: default
          class: logging.StreamHandler
          stream: ext://sys.stderr
        access:
          formatter: access
          class: logging.StreamHandler
          stream: ext://sys.stdout
      loggers:
        uvicorn:
          level: INFO
          handlers:
            - default
          propagate: no
        uvicorn.error:
          level: INFO
        uvicorn.access:
          level: INFO
          handlers:
            - access
          propagate: no
