fullnameOverride: tails-server

# Because we don't have a RWX StorageClass in the local Kind cluster
replicaCount: 1

podAnnotations:
  sidecar.istio.io/proxyCPU: 10m
  ad.datadoghq.com/tails-server.logs: '[{"source": "python.acapy", "service": "tails-server"}]'
podLabels:
  admission.datadoghq.com/enabled: "true"

image:
  name: acapy-cloud/tails-server
  pullPolicy: Always
  tag: master

ingressDomain: cloudapi.127.0.0.1.nip.io
ingress:
  internal:
    enabled: true
    className: nginx
    rules:
      - host: tails-server.{{ .Values.ingressDomain }}
command:
  - poetry
  - run
  - uvicorn
  - tails.main:app
  - --log-config=/tmp/log_conf.yaml
  - --reload
  - --host
  - 0.0.0.0
  - --port
  - 6543

service:
  port: 6543
  containerPort: 6543
  appProtocol: tcp

livenessProbe:
  httpGet:
    port: 6543
    path: /health/live
readinessProbe:
  httpGet:
    port: 6543
    path: /health/ready
  initialDelaySeconds: 5

persistence:
  enabled: false

extraVolumes:
  - name: tmp-tails
    emptyDir: {}
extraVolumeMounts:
  - name: tmp-tails
    mountPath: /tmp/tails

podSecurityContext:
  fsGroup: 65534
securityContext:
  runAsUser: 65534

# resources:
#   requests:
#     cpu: 50m
#     memory: 128Mi
#   limits:
#     cpu: 250m
#     memory: 256Mi
