fullnameOverride: tails-server

# Because we don't have a RWX StorageClass in the local Kind cluster
replicaCount: 1

podAnnotations:
  sidecar.istio.io/proxyCPU: 10m
  ad.datadoghq.com/tails-server.logs: '[{"source": "python.acapy", "service": "tails-server"}]'
podLabels:
  admission.datadoghq.com/enabled: "true"

image:
  name: d-cloud/tails-server
  # registry: ghcr.io/bcgov
  # tag: 1.1
  pullPolicy: Always
  tag: master

ingressDomain: cloudapi.127.0.0.1.nip.io
ingress:
  internal:
    enabled: true
    className: nginx
    rules:
      - host: tails-server.{{ .Values.ingressDomain }}
        paths:
          - path: /
            port: 6543

args:
  - tails-server
  - --host
  - 0.0.0.0
  - --port
  - 6543
  - --storage-path
  - /tails-server-db
  - --log-level
  - INFO

service:
  port: 6543
  containerPort: 6543
  appProtocol: tcp

livenessProbe:
  tcpSocket:
    port: "{{ trunc 15 .Release.Name }}"
readinessProbe:
  tcpSocket:
    port: "{{ trunc 15 .Release.Name }}"
  initialDelaySeconds: 5

persistence:
  enabled: true
  mountPath: /tails-server-db
  capacity: 10Gi
  storageClassName: standard
  accessMode: ReadWriteOnce

podSecurityContext:
  fsGroup: 65534
securityContext:
  runAsUser: 65534

# resources:
#   requests:
#     cpu: 50m
#     memory: 128Mi
#   limits:
#     cpu: 250m
#     memory: 256Mi
