# https://github.com/didx-xyz/bitnami-charts/tree/main/bitnami/minio

global:
  security:
    # Required to override image repositories (`docker.io/bitnami` -> `ghcr.io/didx-xyz/bitnami-oss`)
    # https://github.com/bitnami/charts/issues/35164
    # https://github.com/bitnami/containers/issues/83267
    allowInsecureImages: true
  imageRegistry: ghcr.io

fullnameOverride: minio

image:
  repository: didx-xyz/bitnami-oss/minio
clientImage:
  repository: didx-xyz/bitnami-oss/minio-client
defaultInitContainers:
  volumePermissions:
    image:
      repository: didx-xyz/bitnami-oss/os-shell

auth:
  rootUser: minio # minimum length of 3
  rootPassword: password # minimum length of 8

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: minio-api.127.0.0.1.nip.io

console:
  image:
    repository: didx-xyz/bitnami-oss/minio-object-browser
  podLabels:
    sidecar.istio.io/inject: "false"
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: minio.127.0.0.1.nip.io

updateStrategy:
  type: Recreate
persistence:
  enabled: true
  storageClass: ""
  size: 8Gi

provisioning:
  enabled: true
  podLabels:
    sidecar.istio.io/inject: "false"
  buckets:
    - name: acapy-cloud-public
  extraCommands:
    - mc anonymous set download provisioning/acapy-cloud-public
    - mc anonymous get provisioning/acapy-cloud-public

podLabels:
  sidecar.istio.io/inject: "false"
