# https://github.com/bitnami/charts/tree/main/bitnami/minio

global:
  security:
    # Required to override image repositories (`bitnami` -> `bitnamilegacy`)
    # https://github.com/bitnami/charts/issues/35164
    # https://github.com/bitnami/containers/issues/84600
    allowInsecureImages: true

fullnameOverride: minio

image:
  repository: bitnamilegacy/minio
clientImage:
  repository: bitnamilegacy/minio-client
defaultInitContainers:
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell

auth:
  rootUser: minio # minimum length of 3
  rootPassword: password # minimum length of 8

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: minio-api.127.0.0.1.nip.io

console:
  image:
    repository: bitnamilegacy/minio-object-browser
  podLabels:
    sidecar.istio.io/inject: "false"
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: minio.127.0.0.1.nip.io

updateStrategy:
  type: Recreate
persistence:
  enabled: true
  storageClass: ""
  size: 8Gi

provisioning:
  enabled: true
  podLabels:
    sidecar.istio.io/inject: "false"
  buckets:
    - name: acapy-cloud-public
  extraCommands:
    - mc anonymous set download provisioning/acapy-cloud-public
    - mc anonymous get provisioning/acapy-cloud-public

podLabels:
  sidecar.istio.io/inject: "false"
