# https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha
fullnameOverride: cloudapi
postgresql:
  podAnnotations:
    sidecar.istio.io/proxyCPU: 10m
  podLabels:
    sidecar.istio.io/inject: "false"
    tags.datadoghq.com/env: local
  # Due to bug in Askar (https://github.com/hyperledger/aries-askar/issues/299)
  # we can't use PGPool on first boot and we need to guarantee that we talk to
  # the primary Postgres instance.
  # So we set replicaCount to 1 to avoid accidentally talking to a RO replica.
  replicaCount: 1
  username: postgres
  password: postgres
  repmgrUsername: repmgr
  repmgrPassword: repmgr
  initdbScripts: # Runs on first boot
    init.sh: |-
      #!/bin/sh
      PGPASSWORD=postgres psql -v ON_ERROR_STOP=1 --username postgres --no-password --dbname postgres <<-EOSQL
        CREATE USER "trust-registry" WITH PASSWORD 'trust-registry';
        CREATE DATABASE "trust-registry" WITH OWNER "trust-registry" CONNECTION LIMIT -1;

        CREATE USER governance WITH PASSWORD 'governance' CREATEDB;
        CREATE USER multitenant WITH PASSWORD 'multitenant' CREATEDB;
        CREATE USER mediator WITH PASSWORD 'mediator' CREATEDB;
      EOSQL
  # https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  resourcesPreset: none
  maxConnections: 4500 # pgpool.numInitChildren * pgpool.maxPool
persistentVolumeClaimRetentionPolicy:
  enabled: true
  whenDeleted: Delete
pgpool:
  podAnnotations:
    sidecar.istio.io/proxyCPU: 10m
  podLabels:
    sidecar.istio.io/inject: "false"
    tags.datadoghq.com/env: local
  customUsers:
    usernames: trust-registry;governance;multitenant;mediator
    passwords: trust-registry;governance;multitenant;mediator
  adminUsername: admin
  adminPassword: admin
  numInitChildren: 300 # Concurrent connections limit to Pgpool-II from clients
  reservedConnections: 5
  maxPool: 15             # Maximum cached connections per child process
  childMaxConnections: 30 # Maximum client connections per child process
  # https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  resourcesPreset: none
  tls:
    enabled: false
    autoGenerated: true # use self signed cert
  # PostgreSQL 15 -> 16 compatibility
  srCheckUsername: repmgr
  srCheckPassword: repmgr
