# https://github.com/didx-xyz/bitnami-charts/tree/main/bitnami/valkey

global:
  security:
    # Required to override image repositories (`docker.io/bitnami` -> `ghcr.io/didx-xyz/bitnami-oss`)
    # https://github.com/bitnami/charts/issues/35164
    # https://github.com/bitnami/containers/issues/84600
    allowInsecureImages: true
  imageRegistry: ghcr.io

fullnameOverride: valkey
architecture: replication
image:
  repository: didx-xyz/bitnami-oss/valkey
auth:
  enabled: false
primary:
  replicaCount: 1
  resourcesPreset: nano
  persistence:
    enabled: false
    size: 1Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenDeleted: Delete
  podLabels:
    sidecar.istio.io/inject: "false"
  pdb:
    create: false
replica:
  replicaCount: 0
  resourcesPreset: nano
  persistence:
    enabled: false
    size: 1Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenDeleted: Delete
  podLabels:
    sidecar.istio.io/inject: "false"
  podManagementPolicy: Parallel
  pdb:
    create: false
sentinel:
  image:
    repository: didx-xyz/bitnami-oss/valkey-sentinel
metrics:
  image:
    repository: didx-xyz/bitnami-oss/valkey-exporter
volumePermissions:
  image:
    repository: didx-xyz/bitnami-oss/os-shell
kubectl:
  image:
    repository: didx-xyz/bitnami-oss/kubectl
