{{- with .Values.istio.envoyFilter }}
{{- if .enabled }}
# https://istio.io/latest/docs/reference/config/networking/envoy-filter/
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "didx-cloud.fullname" $ }}
  labels:
    {{- include "didx-cloud.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- tpl (toYaml .labels) $ | nindent 4 }}
    {{- end }}
  {{- if .annotations }}
  annotations:
    {{- tpl (toYaml .annotations) $ | nindent 4 }}
  {{- end }}
spec:
  workloadSelector:
    labels:
      {{- include "didx-cloud.selectorLabels" $ | nindent 6 }}
  configPatches:
    {{- tpl (toYaml .patches) $ | nindent 4 }}
{{- end }}
{{- end }}
