{{- range $configName, $configContent := .Values.configFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "acapy-cloud.fullname" $ }}-{{ $configName | replace "_" "" | lower }}"
  labels:
    {{- include "acapy-cloud.labels" $ | nindent 4 }}
data:
  {{ $configName }}: |-
    {{- tpl $configContent.content $ | nindent 4 }}
{{- end }}
