{{- with .Values.istio.auth }}
{{- with .authn }}
{{- if .enabled }}
# https://istio.io/latest/docs/tasks/security/authentication/authn-policy/
# https://istio.io/latest/docs/reference/config/security/request_authentication/
# https://istio.io/latest/docs/reference/config/security/jwt/
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: {{ include "acapy-cloud.fullname" $ }}
  labels:
    {{- include "acapy-cloud.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- tpl (toYaml .labels) $ | nindent 4 }}
    {{- end }}
  {{- if .annotations }}
  annotations:
    {{- tpl (toYaml .annotations) $ | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "acapy-cloud.selectorLabels" $ | nindent 6 }}
  jwtRules:
    {{- tpl (toYaml .conf.jwtRules) $ | nindent 4 }}
{{- end }}
{{- end }}
---
{{- with .authz }}
{{- if .enabled }}
# https://istio.io/latest/docs/reference/config/security/authorization-policy/
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "acapy-cloud.fullname" $ }}
  labels:
    {{- include "acapy-cloud.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- tpl (toYaml .labels) $ | nindent 4 }}
    {{- end }}
  {{- if .annotations }}
  annotations:
    {{- tpl (toYaml .annotations) $ | nindent 4 }}
  {{- end }}
spec:
  action: {{ default "ALLOW" .conf.action }}
  selector:
    matchLabels:
      {{- include "acapy-cloud.selectorLabels" $ | nindent 6 }}
  rules:
    {{- if .conf.rules }}
    {{- tpl (toYaml .conf.rules) $ | nindent 4 }}
    {{- else }}
    - from:
      - source:
          requestPrincipals: ["*"]
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
