{{- with .Values.istio.virtualService }}
{{- if .enabled }}
# https://istio.io/latest/docs/reference/config/networking/virtual-service/
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "acapy-cloud.fullname" $ }}
  labels:
    {{- include "acapy-cloud.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- tpl (toYaml .labels) $ | nindent 4 }}
    {{- end }}
  {{- if .annotations }}
  annotations:
    {{- tpl (toYaml .annotations) $ | nindent 4 }}
  {{- end }}
spec:
  {{- if and .conf.gateways .conf.hosts }}
  gateways:
    {{- range $gw := .conf.gateways }}
    - {{ tpl $gw $ }}
    {{- end }}
  {{- else if .conf.hosts }}
  gateways:
    - mesh
    - istio-system/istio-internal
  {{- else }}
  gateways: []
  {{- end }}
  {{- if .conf.hosts }}
  hosts:
    {{- range $h := .conf.hosts }}
    - {{ tpl $h $ }}
    {{- end }}
  {{- end }}
  http:
  {{- if .conf.http }}
    {{- tpl (toYaml .conf.http) $ | nindent 4 }}
  {{- else }}
    - name: {{ include "acapy-cloud.fullname" $ }}
      route:
        - destination:
            host: {{ include "acapy-cloud.fullname" $ }}
            port:
              number: {{ $.Values.service.port }}
  {{- end }}
  {{- if .conf.tcp }}
  tcp:
    {{- tpl (.conf.tcp) $ | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
