{{- if not .Values.service.hostNetwork }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acapy-cloud.fullname" . }}
  labels:
    {{- include "acapy-cloud.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.containerPort }}
    protocol: TCP
    name: {{ trunc 15 .Release.Name }}
    {{- with .Values.service.appProtocol }}
    appProtocol: {{ . }}
    {{- end }}
  {{- range .Values.addPorts }}
  - port: {{ .port }}
    targetPort: {{ .containerPort }}
    protocol: {{ .protocol | default "TCP" }}
    {{- if .name }}
    name: {{ tpl .name $ }}
    {{- else }}
    name: {{ .port }}-{{ .protocol | lower | default "tcp" }}
    {{- end }}
    {{- with .appProtocol }}
    appProtocol: {{ . }}
    {{- end }}
  {{- end }}
  {{- range $index, $port := .Values.addPortsRange }}
  {{- range untilStep ( .minPort | int ) ( add1 .maxPort | int ) 1 }}
  - port: {{ . }}
    targetPort: {{ . }}
    protocol: {{ $port.protocol | default "TCP" }}
    {{- if $port.name }}
    name: {{ tpl $port.name $ }}
    {{- else }}
    name: {{ . }}-{{ $port.protocol | lower | default "tcp" }}
    {{- end }}
    {{- with .appProtocol }}
    appProtocol: {{ . }}
    {{- end }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "acapy-cloud.selectorLabels" . | nindent 4 }}
{{- end }}
