{{- with .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cheqd.fullname" $ }}
  labels:
    {{- include "cheqd.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- if .validatorKey }}
  priv_validator_key.json: |-
    {{- tpl (toPrettyJson .validatorKey) $ | nindent 4 }}
  {{- end }}
  {{- if .nodeKey }}
  node_key.json: |-
    {{- tpl (toPrettyJson .nodeKey) $ | nindent 4 }}
  {{- end }}
  {{- if .validatorMnemonic }}
  validator_mnemonic: {{ .validatorMnemonic | quote }}
  {{- end }}
{{- end }}
