apiVersion: v1
kind: Service
metadata:
  name: {{ include "cheqd.fullname" . }}
  labels:
    {{- include "cheqd.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.rosettaPort }}
      targetPort: rosetta
      protocol: TCP
      name: rosetta
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.grpcWebPort }}
      targetPort: grpc-web
      protocol: TCP
      name: grpc-web
  selector:
    {{- include "cheqd.selectorLabels" . | nindent 4 }}
{{- if .Values.lbService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cheqd.fullname" . }}-lb
  labels:
    {{- include "cheqd.labels" . | nindent 4 }}
  {{- with .Values.lbService.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
    {{- tpl (toYaml .Values.lbService.ports) $ | nindent 4 }}
  selector:
    {{- include "cheqd.selectorLabels" . | nindent 4 }}
{{- end }}
