{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cheqd.serviceAccountName" . }}
  labels:
    {{- include "cheqd.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{ if .Values.lbService.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cheqd.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cheqd.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cheqd.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "cheqd.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
