[book]
authors = ["cl0ete","ff137"]
language = "en"
multilingual = false
src = "src"
title = "acapy-cloud"
[preprocessor.mermaid]

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
