[book]
authors = ["cl0ete"]
language = "en"
multilingual = false
src = "src"
title = "DIDx-Cloud"
[preprocessor.mermaid]

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
