apiVersion: v1
kind: ConfigMap
metadata:
  name: ips-configmap
data:
  IPS: |
    ledger-nodes-0.ledger-nodes-headless.{{ .Release.Namespace }}.svc.cluster.local,
    ledger-nodes-1.ledger-nodes-headless.{{ .Release.Namespace }}.svc.cluster.local,
    ledger-nodes-2.ledger-nodes-headless.{{ .Release.Namespace }}.svc.cluster.local,
    ledger-nodes-3.ledger-nodes-headless.{{ .Release.Namespace }}.svc.cluster.local
