apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ledger-nodes.fullname" . }}-ips
  labels:
    {{- include "ledger-nodes.labels" . | nindent 4 }}
data:
  IPS: |
    ledger-nodes-0.ledger-nodes-headless.{{ .Release.Namespace }}.svc.cluster.local,
    ledger-nodes-1.ledger-nodes-headless.{{ .Release.Namespace }}.svc.cluster.local,
    ledger-nodes-2.ledger-nodes-headless.{{ .Release.Namespace }}.svc.cluster.local,
    ledger-nodes-3.ledger-nodes-headless.{{ .Release.Namespace }}.svc.cluster.local
