name: Deploy to ECR

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  deploy:
    name: Build image and push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Check out code and build
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          #ECR_REPOSITORY: cloud_api
          IMAGE_TAG: development
          #DOCKER_REGISTRY=324190738845.dkr.ecr.af-south-1.amazonaws.com/cloud_api
          #DOCKER_REGISTRY=324190738845.dkr.ecr.af-south-1.amazonaws.com

        run: |
          #docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          #docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
          #bash ./scripts/git_update.sh -v minor
          bash ./scripts/install_latest_docker-compose.sh
          #bash /usr/local/bin/python -m pip install --upgrade pip
          #bash ./scripts/create_ecr_repos.sh -v ${ECR_REGISTRY}
          #bash create_ecr_repos.sh
          
          docker-compose build
          docker-compose push
