# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Build

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          [
            app/tests/e2e/test_definitions.py,
            app/tests/e2e/issuer/did_sov/test_v2_indy.py,
            app/tests/e2e/issuer/did_sov/test_v1_indy.py,
            endorser,
            trustregistry,
            webhooks,
            app --ignore=app/tests/e2e/test_definitions.py --ignore=app/tests/e2e/issuer/did_sov/test_v2_indy.py --ignore=app/tests/e2e/issuer/did_sov/test_v1_indy.py,
          ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install test dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Pylint on ${{ matrix.module }}
        run: |
          pylint ${{ matrix.module }} --rcfile=.pylintrc -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --exit-zero > pylintreport.txt
      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          legacy: true # will also install in PATH as `docker-compose`
      - name: Start Test Harness
        run: |
          set -x
          docker compose version
          rm -rf ./data
          mkdir ./data
          sudo chown -R $(id -u):$(id -g) ./data
          chmod 777 ./data -R
          chmod u+x manage
          i=0
          echo waiting for aca-py container to startup
          ./manage up-daemon-usecache
        shell: bash
      - name: Test with pytest on ${{ matrix.module }}
        id: test
        run: |
          pytest --durations=0 --cov=${{ matrix.module }} ${{ matrix.module }}
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
          echo done
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }} # Needed for Codacy reporting
