# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Build

on:
  push:
    branches: [development, feature/*, main]
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: Install test dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt -r requirements.dev.txt -r trustregistry/requirements.txt
      - name: Install docker-compose with pip
        run: pip install docker-compose
      - name: Start Test Harness
        run: |
          chmod u+x manage
          ./manage up-daemon-usecache
          i=0
          echo echo waiting for dockers to startup
          while [ $i -le 2 ]
          do
            if (docker logs $(docker ps -f name="yoma-ga-agent" | awk 'FNR == 2 {print $1}') | grep -q "::::::::::::::::::::::::::::::::::::::::::::::
            :: Alice                                    ::
            ::                                          ::
            ::                                          ::
            :: Inbound Transports:                      ::
            ::                                          ::
            :: "); echo wait over; exit 0; then ((i++)); fi
          done
        shell: bash
      - name: Test with pytest
        id: test
        continue-on-error: true
        run: |
          docker-compose up --build -d yoma-ga-agent
          docker-compose up --build -d yoma-multitenant-agent
          sleep 120
          pytest  --cov=trustregistry --cov=app trustregistry app
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
          echo done
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }} # Needed for Codacy reporting
      - name: Retry tests
        if: steps.test.outcome=='failure' # check the step outcome, retry 1st time
        run: |
          docker-compose up --build -d yoma-ga-agent
          docker-compose up --build -d yoma-multitenant-agent
          sleep 120
          pytest trustregistry app --cov=trustregistry --cov=app --ignore=webhooks --log-cli-level=1
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
          echo done
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }} # Needed for Codacy reporting
      - name: Run Pylint
        run: |
          pylint app --rcfile=.pylintrc -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --exit-zero > pylintreport.txt
      - name: Tear down test harness
        run: |
          ./manage down || true
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        if: github.ref == 'refs/heads/development' && github.repository == 'didx-xyz/aries-cloudapi-python' && github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd aries-cloudapi-python
            git pull
            make stop_n_clean
            ./manage up-as-daemon

