# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Build

on:
  push:
    branches: [ development, feature/*, main ]
  pull_request:
    branches: [ development ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Start Test Harness
      run: |
       chmod u+x manage
        ./manage up-as-daemon
       echo waiting for dockers to startup, sleeping for 60 seconds
       sleep 60
       echo wait over, continuing
    - name: Install test dependencies.
      run: |
        cd app
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        cd app
        pytest --cov --ignore=tests/bdd
        echo done
    - name: Run Pylint
      run: |
        pip install pylint
        pylint app --rcfile=.pylintrc -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --exit-zero > pylintreport.txt
    - name: Tear down test harnless
      run: |
       ./manage down || true
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
         -Dsonar.organization=didx-xyz
         -Dsonar.projectKey=didx-xyz_aries-cloudapi-python
         -Dsonar.verbose=false
         -Dsonar.python.xunit.reportPath=junit.xml
         -Dsonar.python.coverage.reportPaths=coverage.xml
         -Dsonar.python.pylint.reportPaths=pylintreport.txt
         -Dsonar.projectBaseDir=./app
         -Dsonar.coverage.exclusions=tests/**/*


