name: Python code style check

on:
  pull_request:
    branches:
      - master

jobs:
  style:
    name: style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: jdx/mise-action@v2
        with:
          cache: true
          experimental: true
          mise_toml: |
            [tools]
            "pipx:black" = "24.10"
            "pipx:isort" = "5.13"
            python = "3.12"
            uv = "0.4"

            [settings]
            pipx_uvx = true

      - name: Check import style with isort
        run: isort . --check --profile black --diff

      - name: Check code style with Black
        run: black . --check --diff

      - name: Check Tiltfiles with Black
        run: |
          find . -type f -name "Tiltfile" | while read -r file; do
            black --check --diff "$file"
          done
